apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-hello
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - uses: docker://caternberg/ci-toolbox
        name: curltest
        run: curl https://api.github.com/users/cccaternberg
